name: "scd:passive:ground_truth"
description: |
  Detect changes between two scenes of an environment. An object map describes each changed object with a probabilistic label suggestion, spatial location, and probabilistic state change suggestion (added, removed, changed). This task provides passive robot control, and sensor observations with ground truth robot pose.
type: sim_unreal
actions:
  - move_next
observations:
  - image_depth
  - image_depth_info
  - image_rgb
  - image_rgb_info
  - laser
  - poses
results_format: object_map_with_states
scene_count: 2
