name: "semantic_slam:passive:ground_truth"
description: |
  Use a Semantic SLAM algorithm to construct an object map of the environment. An object map describes each object with a probabilistic label suggestion, spatial location, and optional probabilistic state change suggestion. This task provides passive robot control, and sensor observations with ground truth robot pose.
type: sim_unreal
actions:
  - move_next
observations:
  - image_depth
  - image_depth_info
  - image_rgb
  - image_rgb_info
  - laser
  - poses
results_format: object_map
